import { test, expect } from '@playwright/test';

test('Squad editing, presets, power and roster removal persist on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#/heroes');
  await page.locator('#hero-search').fill('Arthur');
  await page.locator('.catalog-hero-actions button').click();
  await page.goto('/#/my-heroes');
  await expect(page.getByRole('button', { name: 'Augmenter la puissance', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Augmenter la puissance', exact: true }).click();
  await expect(page.locator('#hero-power')).toHaveValue('');
  await page.locator('.squad-power-field .stock-increment').nth(1).click();
  await expect(page.locator('#hero-power')).toHaveValue('1000');
  await page.getByRole('button', { name: 'Diminuer la puissance', exact: true }).click();
  await expect(page.locator('#hero-power')).toHaveValue('1000');
  await page.locator('.squad-power-field .stock-increment').nth(2).click();
  await expect(page.locator('#hero-power')).toHaveValue('0');
  await page.locator('#hero-power').fill('');
  await page.reload();
  await expect(page.locator('#hero-power')).toHaveValue('');
  await page.locator('#hero-power').fill('1233');
  await page.getByRole('button', { name: 'Augmenter la puissance', exact: true }).click();
  await page.locator('.squad-power-field .stock-increment').first().click();
  await expect(page.locator('#hero-power')).toHaveValue('1234');
  await page.locator('#hero-current').selectOption('2');
  await expect(page.locator('#hero-target')).toHaveValue('2');
  await expect(page.locator('#hero-target option').first()).toHaveValue('2');
  await page.locator('#hero-target').selectOption('10');
  await page.locator('#hero-current').selectOption('5');
  await expect(page.locator('#hero-target')).toHaveValue('10');
  await page.locator('#hero-current').selectOption('1');
  await expect(page.locator('#hero-target')).toHaveValue('10');
  const maximumLevel = await page.locator('#hero-current option').last().getAttribute('value');
  await page.locator('#hero-current').selectOption(maximumLevel!);
  await expect(page.locator('#hero-target')).toHaveValue(maximumLevel!);
  await expect(page.locator('#hero-target option')).toHaveCount(1);
  await page.reload();
  await expect(page.locator('#hero-target')).toHaveValue(maximumLevel!);
  await expect(page.locator('#hero-power')).toHaveValue('1234');
  await page.getByRole('button', { name: 'Escouades', exact: true }).click();
  await expect(page.locator('.squad-slot')).toHaveCount(5);
  await expect(page.locator('.squad-slot > small')).toHaveText(['Avant · 1', 'Avant · 2', 'Arrière · 3', 'Arrière · 4', 'Arrière · 5']);
  const positions = await page.locator('.squad-slot').evaluateAll(elements => elements.map(element => { const rect = element.getBoundingClientRect(); return { top: rect.top, left: rect.left }; }));
  expect(positions[0].top).toBe(positions[1].top);
  expect(positions[2].top).toBeGreaterThan(positions[0].top);
  expect(positions[2].top).toBe(positions[3].top);
  expect(positions[3].top).toBe(positions[4].top);
  expect(positions[3].left).toBeGreaterThan(positions[2].left);
  expect(positions[4].left).toBeGreaterThan(positions[3].left);
  await page.locator('.squad-slot').first().click();
  await page.locator('dialog .tracked-hero').click();
  await expect(page.locator('.squad-heading strong')).toContainText(/1.*234/);
  await page.locator('.squad-slot').nth(1).click();
  await expect(page.locator('dialog .tracked-hero')).toBeDisabled();
  await page.keyboard.press('Escape');
  await page.locator('.squad-save input').fill('Duel');
  await page.locator('.squad-save button').click();
  await page.getByRole('button', { name: 'Escouade 2', exact: true }).click();
  await page.locator('.squad-workspace select').selectOption({ label: 'Duel' });
  await page.getByRole('button', { name: 'Appliquer', exact: true }).click();
  await expect(page.locator('.squad-slot').first()).toContainText('Arthur');
  await page.screenshot({ path: '/tmp/lat-squads-mobile.png', fullPage: true });
  await page.reload();
  await expect(page.locator('.squad-power-field input')).toHaveValue('1234');
  await page.getByRole('button', { name: 'Presets', exact: true }).click();
  await page.locator('.squad-preset input').fill('Boss');
  await page.locator('.squad-preset input').press('Tab');
  await page.reload();
  await page.getByRole('button', { name: 'Presets', exact: true }).click();
  await expect(page.locator('.squad-preset input')).toHaveValue('Boss');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Héros', exact: true }).click();
  await page.locator('.hero-details > .text-btn').click();
  await page.getByRole('button', { name: 'Escouades', exact: true }).click();
  await expect(page.locator('.squad-slot.occupied')).toHaveCount(0);
  await page.getByRole('button', { name: 'Presets', exact: true }).click();
  await expect(page.locator('.squad-preset p')).not.toContainText('Arthur');
  await page.locator('.squad-preset .text-btn').click();
  await expect(page.locator('.squad-preset')).toHaveCount(0);
  await page.locator('[data-lang="fr"]').click();
  await page.locator('[data-lang="en"]').click();
  await page.getByRole('button', { name: 'Squads', exact: true }).click();
  await expect(page.locator('.squad-heading h3')).toHaveText('Squad 1');
  await page.reload();
  await page.getByRole('button', { name: 'Presets', exact: true }).click();
  await expect(page.locator('.squad-preset')).toHaveCount(0);
});

test('Shared adjustment buttons retain the stock interaction', async ({ page }) => {
  await page.goto('/#/stocks');
  const field = page.locator('.quick-stock-field').filter({ has: page.locator('#stock-antitoxin') });
  const value = field.locator('input');
  await value.fill('0');
  await field.getByRole('button', { name: '+1M', exact: true }).click();
  await expect(value).toHaveValue(/1\s000\s000/);
  await field.getByRole('button', { name: 'Retirer', exact: true }).click();
  await expect(value).toHaveValue(/1\s000\s000/);
  await field.getByRole('button', { name: '−1M', exact: true }).click();
  await expect(value).toHaveValue('0');
});
